# CI de Nível 01 - disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'execução manual'

#regras de disparo (gatilhos/triggers)
#gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

#jobs = tarefas que serão executadas
jobs:
  #nome do job
  e2e-tests:
    #especifica o ambiente onde o job será executado
    runs-on: ubuntu-latest

    #passos que serão executados nesse job
    steps:
      #clone do projeto
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
         node-version: 22.x
      
      #instalação do yarn
      - name: instalando Yarn
        run: npm install -g yarn
      
      #instalação das dependências do projeto
      - name: instalando dependências
        run: yarn 

      #instalacao do playwright
      - name: instalando Playwright
        run: yarn playwright install

      #execução dos testes e2e
      - name: executando testes e2e
        run: yarn run e2e