# CI de Nível 04 - disparo dos testes dentro do pipe de dev

name: 'execução integrada'

on:
  workflow_dispatch:
    
jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: instalando yarn
        run: npm install -g yarn

      - name: instalando dependências
        run: yarn
        
      - name: checando padronização de código
        run: yarn lint   
  
  unidade:
    needs: inspecao
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: instalando yarn
        run: npm install -g yarn

      - name: instalando dependências
        run: yarn

      - name: executando testes de unidade
        run: yarn test 
  
  e2e-tests:
    needs: unidade
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      
      - name: instalando Yarn
        run: npm install -g yarn
      
      - name: instalando dependências
        run: yarn

      - name: instalando Playwright
        run: yarn playwright install

      - name: executando testes e2e
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report
  
  deploy:
    needs: e2e-tests
    runs-on: ubuntu-latest

    steps:
      - name: simulação de deploy
        run: echo "Deploy realizado com sucesso!"
